/*
 * Lenra server internal API
 * The API usable by the Lenra applications
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lenra.api.internal.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InsertManyDocuments200Response
 */
public class InsertManyDocuments200ResponseTest {
    private final InsertManyDocuments200Response model = new InsertManyDocuments200Response();

    /**
     * Model tests for InsertManyDocuments200Response
     */
    @Test
    public void testInsertManyDocuments200Response() {
        // TODO: test InsertManyDocuments200Response
    }

    /**
     * Test the property 'insertedIds'
     */
    @Test
    public void insertedIdsTest() {
        // TODO: test insertedIds
    }

}
