/*
 * Lenra server internal API
 * The API usable by the Lenra applications
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lenra.api.internal.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateManyDocumentsRequest
 */
public class UpdateManyDocumentsRequestTest {
    private final UpdateManyDocumentsRequest model = new UpdateManyDocumentsRequest();

    /**
     * Model tests for UpdateManyDocumentsRequest
     */
    @Test
    public void testUpdateManyDocumentsRequest() {
        // TODO: test UpdateManyDocumentsRequest
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'update'
     */
    @Test
    public void updateTest() {
        // TODO: test update
    }

}
